"""
secret_loader.py

This script decrypts an AES-encrypted secrets file generated by a GitHub Action and permanently sets
the contained key-value pairs as user-level environment variables.

It is designed for use on a personal machine where GitHub Actions cannot directly modify the environment.
"""
