name: Export GitHub Secrets to Encrypted ZIP

on:
  workflow_dispatch:

jobs:
  backup-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: Create .env file from secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> secrets.env

      - name: Install zip with encryption support
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Encrypt secrets.env into secrets.zip
        run: zip --password "${{ secrets.ARCHIVE_PASSWORD }}" secrets.zip secrets.env

      - name: Upload encrypted secrets.zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-secrets-backup
          path: secrets.zip
