name: Export GitHub Secrets to Encrypted ENV (OpenSSL AES)

on:
  workflow_dispatch:

jobs:
  backup-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: Create secrets.env from GitHub Secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> secrets.env

      - name: Encrypt secrets.env using OpenSSL AES-256-CBC
        run: |
          openssl enc -aes-256-cbc -salt -in secrets.env -out secrets.env.enc -pass pass:"${{ secrets.ARCHIVE_PASSWORD }}"

      - name: Upload encrypted secrets.env.enc as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-secrets-encrypted
          path: secrets.env.enc
