name: Export GitHub Secrets to Encrypted ZIP

on:
  workflow_dispatch:

jobs:
  backup-secrets:
    runs-on: windows-latest
    steps:
      - name: Create .env file from secrets
        run: |
          echo DB_USER=${{ secrets.DB_USER }} >> secrets.env
          echo DB_PASS=${{ secrets.DB_PASS }} >> secrets.env
          echo API_KEY=${{ secrets.API_KEY }} >> secrets.env

      - name: Install 7-Zip
        run: choco install 7zip -y

      - name: Encrypt secrets.env into secrets.zip
        shell: pwsh
        run: |
          & "C:\""Program Files""\7-Zip\7z.exe" a -p${{ secrets.ARCHIVE_PASSWORD }} secrets.zip secrets.env

      - name: Upload encrypted secrets.zip as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: env-secrets-backup
          path: secrets.zip
